name: Terraform Destroy
on: workflow_dispatch
permissions: {id-token: write, contents: read}
env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
  FRONTEND_ECR_REPOSITORY: ${{ vars.FRONTEND_ECR_REPOSITORY }}
  PRODUCT_API_ECR_REPOSITORY: ${{ vars.PRODUCT_API_ECR_REPOSITORY }}
jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults: {run: {working-directory: terraform}}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform destroy -auto-approve
